from pathlib import Path

import cv2
import numpy as np

OBJ_THRESH, NMS_THRESH, IMG_SIZE = 0.25, 0.45, 640
BASE_DIR = Path(__file__).resolve().parent
CLASS_FILE = BASE_DIR / "plant_det.txt"


def load_classes(file_path):
    with open(file_path, "r", encoding="utf-8") as file:
        classes = [line.strip() for line in file.readlines() if line.strip()]
    return tuple(classes)


CLASSES = load_classes(CLASS_FILE)

_LABEL_ZH = {
    "Apple___Apple_scab": "苹果 / 疮痂病",
    "Apple___Black_rot": "苹果 / 黑腐病",
    "Apple___Cedar_apple_rust": "苹果 / 雪松锈病",
    "Apple___healthy": "苹果 / 健康",
    "Blueberry___healthy": "蓝莓 / 健康",
    "Cherry___Powdery_mildew": "樱桃 / 白粉病",
    "Cherry___healthy": "樱桃 / 健康",
    "Corn___Cercospora_leaf_spot Gray_leaf_spot": "玉米 / 灰斑病",
    "Corn___Common_rust": "玉米 / 普通锈病",
    "Corn___Northern_Leaf_Blight": "玉米 / 北方叶枯病",
    "Corn___healthy": "玉米 / 健康",
    "Grape___Black_rot": "葡萄 / 黑腐病",
    "Grape___Esca_(Black_Measles)": "葡萄 / 黑麻疹病",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "葡萄 / 叶枯病",
    "Grape___healthy": "葡萄 / 健康",
    "Orange___Haunglongbing_(Citrus_greening)": "橙子 / 黄龙病",
    "Peach___Bacterial_spot": "桃子 / 细菌性斑点病",
    "Peach___healthy": "桃子 / 健康",
    "Pepper,_bell___Bacterial_spot": "甜椒 / 细菌性斑点病",
    "Pepper,_bell___healthy": "甜椒 / 健康",
    "Potato___Early_blight": "土豆 / 早疫病",
    "Potato___Late_blight": "土豆 / 晚疫病",
    "Potato___healthy": "土豆 / 健康",
    "Raspberry___healthy": "覆盆子 / 健康",
    "Soybean___healthy": "大豆 / 健康",
    "Squash___Powdery_mildew": "南瓜 / 白粉病",
    "Strawberry___Leaf_scorch": "草莓 / 叶焦病",
    "Strawberry___healthy": "草莓 / 健康",
    "Tomato___Bacterial_spot": "番茄 / 细菌性斑点病",
    "Tomato___Early_blight": "番茄 / 早疫病",
    "Tomato___Late_blight": "番茄 / 晚疫病",
    "Tomato___Leaf_Mold": "番茄 / 叶霉病",
    "Tomato___Septoria_leaf_spot": "番茄 / 斑枯病",
    "Tomato___Spider_mites Two-spotted_spider_mite": "番茄 / 红蜘蛛",
    "Tomato___Target_Spot": "番茄 / 靶斑病",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "番茄 / 黄化曲叶病毒病",
    "Tomato___Tomato_mosaic_virus": "番茄 / 花叶病毒病",
    "Tomato___healthy": "番茄 / 健康",
}

_SPECIES_ZH = {
    "Lactuca virosa": "毒莴苣",
    "Pelargonium capitatum": "头状天竺葵",
    "Pelargonium graveolens": "香叶天竺葵",
    "Cirsium arvense": "丝路蓟",
    "Cirsium vulgare": "翼蓟",
    "Pelargonium odoratissimum": "苹果天竺葵",
    "Pelargonium peltatum": "盾叶天竺葵",
    "Pelargonium quercifolium": "栎叶天竺葵",
    "Pelargonium zonale": "马蹄纹天竺葵",
    "Mercurialis annua": "一年生山靛",
    "Phyllanthus tenellus": "柔弱叶下珠",
    "Hypericum perforatum": "贯叶连翘",
    "Egeria densa": "伊乐藻",
    "Ibicella lutea": "黄单角胡麻",
    "Tradescantia fluminensis": "白花紫露草",
    "Tradescantia zebrina": "吊竹梅",
    "Lamium amplexicaule": "宝盖草",
    "Lavandula dentata": "齿叶薰衣草",
    "Striga asiatica": "独脚金",
    "Melilotus albus": "白花草木樨",
    "Trifolium fragiferum": "草莓三叶草",
    "Asystasia gangetica": "宽叶十万错",
    "Nymphaea nouchali": "延药睡莲",
    "Dryopteris aemula": "似鳞毛蕨",
    "Dryopteris affinis": "近亲鳞毛蕨",
    "Dryopteris filix-mas": "欧洲鳞毛蕨",
    "Nephrolepis cordifolia": "肾蕨",
    "Nephrolepis exaltata": "高大肾蕨",
    "Osmunda regalis": "欧紫萁",
    "Achyranthes aspera": "土牛膝",
    "Lithodora fruticosa": "灌状石韦",
    "Humulus lupulus": "啤酒花",
    "Vaccaria hispanica": "麦蓝菜",
    "Spergularia rubra": "红茎拟漆姑",
    "Moehringia trinervia": "三脉种阜草",
    "Calendula officinalis": "金盏花",
    "Calendula stellata": "星状金盏花",
    "Carthamus caeruleus": "蓝红花",
    "Carthamus lanatus": "毛红花",
    "Cirsium monspessulanum": "蒙彼利埃蓟",
    "Helminthotheca echioides": "刚毛菊",
    "Hyoseris radiata": "辐射猪菊苣",
    "Lactuca muralis": "墙生莴苣",
    "Lactuca saligna": "柳叶莴苣",
    "Lactuca tenerrima": "极细莴苣",
    "Limbarda crithmoides": "海蓬菊",
    "Sedum acre": "辛辣景天",
    "Sedum album": "白景天",
    "Sedum amplexicaule": "抱茎景天",
    "Sedum andegavense": "昂热景天",
    "Sedum brevifolium": "短叶景天",
    "Sedum caeruleum": "蓝景天",
    "Sedum caespitosum": "簇生景天",
    "Sedum cepaea": "葱叶景天",
    "Sedum dasyphyllum": "毛叶景天",
    "Sedum forsterianum": "福斯特景天",
    "Sedum hirsutum": "毛景天",
    "Sedum litoreum": "海滨景天",
    "Sedum multiceps": "多头景天",
    "Sedum rubens": "红景天",
    "Sedum sediforme": "景天状景天",
    "Alliaria petiolata": "葱芥",
    "Boscia angustifolia": "狭叶博斯木",
    "Fibigia clypeata": "盾状草",
    "Maerua angolensis": "安哥拉梅鲁木",
    "Acalypha virginica": "弗吉尼亚铁苋菜",
    "Mercurialis perennis": "宿根山靛",
    "Phyllanthus reticulatus": "网脉叶下珠",
    "Hypericum androsaemum": "雄黄兰金丝桃",
    "Hypericum australe": "南方金丝桃",
    "Hypericum canariense": "加那利金丝桃",
    "Hypericum empetrifolium": "岩高兰叶金丝桃",
    "Hypericum hircinum": "山羊金丝桃",
    "Hypericum hirsutum": "毛金丝桃",
    "Hypericum humifusum": "平卧金丝桃",
    "Hypericum linariifolium": "柳穿鱼叶金丝桃",
    "Hypericum montanum": "山地金丝桃",
    "Hypericum perfoliatum": "贯叶金丝桃",
    "Hypericum tetrapterum": "四翼金丝桃",
    "Hypericum tomentosum": "绒毛金丝桃",
    "Lamium bifidum": "裂叶野芝麻",
    "Lamium flexuosum": "弯曲野芝麻",
    "Lamium garganicum": "加加诺野芝麻",
    "Lamium hybridum": "杂种野芝麻",
    "Lamium purpureum": "紫花野芝麻",
    "Lavandula canariensis": "加那利薰衣草",
    "Lavandula minutolii": "米努托薰衣草",
    "Lavandula multifida": "多裂薰衣草",
    "Lavandula stoechas": "法国薰衣草",
    "Acacia mellifera": "蜜金合欢",
    "Acacia seyal": "塞伊尔金合欢",
    "Acacia tortilis": "扭叶金合欢",
    "Galega officinalis": "山羊豆",
    "Lupinus cosentinii": "科森蒂尼羽扇豆",
    "Lupinus micranthus": "小花羽扇豆",
    "Melilotus italicus": "意大利草木樨",
    "Melilotus sulcatus": "沟草木樨",
    "Trifolium angustifolium": "狭叶三叶草",
    "Trifolium arvense": "兔足三叶草",
    "Trifolium aureum": "金黄三叶草",
    "Trifolium campestre": "田野三叶草",
    "Trifolium cherleri": "切勒三叶草",
    "Trifolium hirtum": "毛三叶草",
    "Trifolium hybridum": "杂种三叶草",
    "Trifolium incarnatum": "绛三叶草",
    "Trifolium lappaceum": "芒刺三叶草",
    "Trifolium michelianum": "米歇尔三叶草",
    "Trifolium micranthum": "小花三叶草",
    "Trifolium montanum": "山地三叶草",
    "Trifolium ochroleucon": "淡黄三叶草",
    "Trifolium pannonicum": "匈牙利三叶草",
    "Trifolium patens": "展开三叶草",
    "Trifolium pratense": "红三叶草",
    "Trifolium purpureum": "紫三叶草",
    "Trifolium resupinatum": "反曲三叶草",
    "Trifolium scabrum": "粗糙三叶草",
    "Trifolium spumosum": "泡沫三叶草",
    "Trifolium squamosum": "鳞状三叶草",
    "Trifolium stellatum": "星状三叶草",
    "Trifolium striatum": "条纹三叶草",
    "Trifolium subterraneum": "地下三叶草",
    "Trifolium tomentosum": "绒毛三叶草",
    "Punica granatum": "石榴",
    "Alcea rosea": "蜀葵",
    "Althaea cannabina": "麻叶药蜀葵",
    "Althaea officinalis": "药蜀葵",
    "Nymphaea alba": "白睡莲",
    "Hunnemannia fumariifolia": "荷包牡丹叶墨西哥罂粟",
    "Papaver atlanticum": "大西洋罂粟",
    "Papaver rupifragum": "岩罂粟",
    "Goniolimon tataricum": "鞑靼棱鳞草",
    "Adonis aestivalis": "夏侧金盏花",
    "Adonis annua": "秋侧金盏花",
    "Adonis flammea": "火焰侧金盏花",
    "Adonis microcarpa": "小果侧金盏花",
    "Anemone coronaria": "冠状银莲花",
    "Anemone palmata": "掌叶银莲花",
    "Oldenlandia corymbosa": "伞房耳草",
    "Hyoscyamus albus": "白天仙子",
    "Hyoscyamus niger": "天仙子",
    "Daphne gnidium": "亚麻叶瑞香",
    "Daphne laureola": "桂叶瑞香",
    "Daphne oleoides": "橄榄叶瑞香",
    "Berula erecta": "直立泽芹",
    "Chaerophyllum temulum": "醉细叶芹",
    "Daucus muricatus": "刺胡萝卜",
    "Meum athamanticum": "波罗门参叶藁本",
    "Thapsia garganica": "加尔加诺毒胡萝卜",
    "Thapsia villosa": "毛毒胡萝卜",
    "Centranthus calcitrapae": "距红缬草",
    "Fedia cornucopiae": "角状败酱",
    "Pancratium canariense": "加那利全能花",
    "Pancratium maritimum": "海滩全能花",
    "Anthericum liliago": "白花鸡尾兰",
    "Butomus umbellatus": "花蔺",
    "Danthonia decumbens": "俯卧扁芒草",
    "Leersia oryzoides": "假稻",
    "Phalaris coerulescens": "天蓝虉草",
    "Oncostema elongata": "长虎眼万年青",
    "Oncostema peruviana": "秘鲁虎眼万年青",
    "Elodea canadensis": "加拿大伊乐藻",
    "Neotinea maculata": "斑点新蒂兰",
    "Ophrys apifera": "蜜蜂蜂兰",
    "Ophrys bombyliflora": "蜂形蜂兰",
    "Ophrys fusca": "暗色蜂兰",
    "Ophrys lutea": "黄花蜂兰",
    "Ophrys scolopax": "鹬形蜂兰",
    "Ophrys speculum": "镜面蜂兰",
    "Ophrys tenthredinifera": "叶蜂形蜂兰",
    "Groenlandia densa": "密格陵兰眼子菜",
    "Myosoton aquaticum": "鹅肠菜",
    "Cirsium palustre": "沼泽蓟",
    "Lamium galeobdolon": "黄野芝麻",
    "Lavandula angustifolia": "狭叶薰衣草",
    "Casuarina cunninghamiana": "细枝木麻黄",
    "Trifolium rubens": "红三叶",
    "Falcaria vulgaris": "镰叶芹",
    "Hypericum triquetrifolium": "三角叶金丝桃",
    "Wigandia caracasana": "加拉加斯威根花",
    "Nymphaea lotus": "齿叶睡莲",
    "Sedum villosum": "毛景天",
    "Epipactis helleborine": "宽叶火烧兰",
    "Thesium humifusum": "平卧百蕊草",
    "Acacia etbaica": "埃塞金合欢",
    "Centranthus angustifolius": "狭叶红缬草",
    "Centranthus lecoqii": "勒科克红缬草",
    "Sedum anglicum": "英国景天",
    "Sedum rupestre": "岩生景天",
    "Ophrys insectifera": "虫形蜂兰",
    "Freesia refracta": "香雪兰",
    "Diatelia tuberaria": "块茎石竹",
    "Tradescantia pallida": "紫竹梅",
    "Cenchrus longispinus": "长刺蒺藜草",
    "Schefflera actinophylla": "辐叶鹅掌柴",
    "Cenchrus clandestinus": "隐生蒺藜草",
    "Cenchrus purpureus": "紫蒺藜草",
    "Cenchrus setaceus": "刚毛蒺藜草",
    "Anemone hortensis": "园银莲花",
    "Tradescantia cerinthoides": "蜡花紫露草",
    "Papaver argemone": "刺罂粟",
    "Papaver hybridum": "杂种罂粟",
    "Papaver rhoeas": "虞美人",
    "Papaver dubium": "长果罂粟",
    "Papaver somniferum": "罂粟",
    "Daucus carota": "野胡萝卜",
    "Smilax aspera": "粗糙菝葜",
    "Aizoon canariense": "加那利阿兹藜",
    "Zannichellia palustris": "角果藻",
    "Secale cereale": "黑麦",
    "Cenchrus ciliaris": "纤毛蒺藜草",
    "Cenchrus echinatus": "刺蒺藜草",
    "Phalaris aquatica": "水虉草",
    "Phalaris arundinacea": "虉草",
    "Phalaris canariensis": "加那利虉草",
    "Phalaris minor": "小虉草",
    "Phalaris paradoxa": "奇异虉草",
    "Sedum hispanicum": "西班牙景天",
    "Crotalaria juncea": "菽麻",
    "Lupinus angustifolius": "狭叶羽扇豆",
    "Lupinus luteus": "黄羽扇豆",
    "Lupinus pilosus": "毛羽扇豆",
    "Lupinus albus": "白羽扇豆",
    "Trifolium alexandrinum": "埃及三叶草",
    "Trifolium dubium": "疑三叶草",
    "Trifolium glomeratum": "球花三叶草",
    "Trifolium nigrescens": "变黑三叶草",
    "Trifolium repens": "白三叶草",
    "Dalbergia melanoxylon": "黑木黄檀",
    "Melilotus indicus": "印度草木樨",
    "Melilotus officinalis": "黄香草木樨",
    "Acacia dealbata": "银荆",
    "Acacia longifolia": "长叶金合欢",
    "Acacia mearnsii": "黑荆",
    "Acacia pycnantha": "密花金合欢",
    "Acacia retinodes": "网叶金合欢",
    "Barbarea verna": "春山芥",
    "Barbarea intermedia": "中间山芥",
    "Myosurus minimus": "小鼠尾草",
    "Fragaria vesca": "森林草莓",
    "Duchesnea indica": "蛇莓",
    "Centranthus ruber": "红缬草",
    "Guizotia abyssinica": "油菊",
    "Tagetes minuta": "印加万寿菊",
    "Tagetes patula": "孔雀草",
    "Calendula arvensis": "野金盏花",
    "Lapsana communis": "欧洲稻槎菜",
    "Carthamus tinctorius": "红花",
    "Lactuca sativa": "生菜",
    "Lactuca serriola": "野莴苣",
    "Arthraxon hispidus": "荩草",
    "Microchloa kunthii": "孔特小草",
    "Harpachne schimperi": "辛珀镰草",
    "Cedrela odorata": "西班牙柏木",
    "Aeschynomene americana": "美国田菁",
    "Prosopis alba": "白牧豆树",
    "Prosopis juliflora": "柔花牧豆树",
    "Crotalaria spectabilis": "大托叶猪屎豆",
    "Crotalaria chrysochlora": "金黄猪屎豆",
    "Crotalaria deflersii": "德弗勒猪屎豆",
    "Crotalaria polysperma": "多籽猪屎豆",
    "Crotalaria uguenensis": "乌格尼猪屎豆",
    "Crotalaria verrucosa": "疣猪屎豆",
    "Lupinus perennis": "宿根羽扇豆",
    "Lupinus polyphyllus": "多叶羽扇豆",
    "Dalbergia latifolia": "阔叶黄檀",
    "Cordyla africana": "非洲心萼豆",
    "Acacia xanthophloea": "黄皮金合欢",
    "Acacia drepanolobium": "镰荚金合欢",
    "Acacia hockii": "霍克金合欢",
    "Acacia angustissima": "极狭金合欢",
    "Gomphocarpus integer": "全缘钉头果",
    "Trachelospermum jasminoides": "络石",
    "Tradescantia spathacea": "蚌花",
    "Gymnosporia putterlickioides": "普特裸实",
    "Conostomium kenyense": "肯尼亚小钟花",
    "Conostomium quadrangulare": "四棱小钟花",
    "Mussaenda frondosa": "多叶玉叶金花",
    "Mussaenda erythrophylla": "红叶玉叶金花",
    "Morinda citrifolia": "海巴戟",
    "Pilocarpus racemosus": "总序毛果芸香",
    "Pelargonium alchemilloides": "羽衣草叶天竺葵",
    "Pelargonium quinquelobatum": "五裂天竺葵",
    "Pelargonium glechomoides": "活血丹叶天竺葵",
    "Gynura aurantiaca": "橙花三七草",
    "Gynura procumbens": "平卧三七草",
    "Tagetes erecta": "万寿菊",
    "Aspilia mossambicensis": "莫桑比克阿菊",
    "Aspilia pluriseta": "多毛阿菊",
    "Schkuhria pinnata": "羽状史库菊",
    "Montanoa hibiscifolia": "木槿叶蒙塔菊",
    "Acalypha crenata": "圆齿铁苋菜",
    "Acalypha hispida": "红穗铁苋菜",
    "Phyllanthus fischeri": "菲舍尔叶下珠",
    "Phyllanthus suffrutescens": "半灌木叶下珠",
    "Phyllanthus acidus": "西印度醋栗",
    "Phyllanthus amarus": "苦味叶下珠",
    "Triadica sebifera": "乌桕",
    "Petiveria alliacea": "蒜臭母鸡草",
    "Peperomia pellucida": "透明椒草",
    "Guaiacum officinale": "愈疮木",
    "Hypericum annulatum": "环纹金丝桃",
    "Mussaenda philippica": "菲律宾玉叶金花",
    "Wigandia urens": "刺威根花",
    "Boscia mossambicensis": "莫桑比克博斯木",
    "Boscia coriacea": "革质博斯木",
    "Mecardonia procumbens": "平卧黄菊英",
    "Browallia americana": "美洲布罗瓦花",
    "Acacia mangium": "马占金合欢",
    "Casuarina equisetifolia": "木麻黄",
    "Aristea abyssinica": "阿比西尼亚蓝星花",
    "Aristea ecklonii": "埃克隆蓝星花",
    "Erianthemum dregei": "德雷格毛冠花",
    "Cucurbita ficifolia": "黑籽南瓜",
    "Cucurbita pepo": "西葫芦",
    "Luffa acutangula": "棱角丝瓜",
    "Lagenaria siceraria": "葫芦",
    "Lagenaria sphaerica": "球形葫芦",
    "Asystasia riparia": "河岸十万错",
    "Barringtonia asiatica": "棋盘脚",
    "Couroupita guianensis": "炮弹树",
    "Asystasia charmian": "查米十万错",
    "Raphia farinifera": "粉酒椰",
    "Zamioculcas zamiifolia": "金钱树",
    "Kniphofia linearifolia": "线叶火炬花",
    "Smilax anceps": "双刃菝葜",
    "Vanilla planifolia": "香荚兰",
    "Ansellia africana": "非洲豹纹兰",
    "Hypericum balearicum": "巴利阿里金丝桃",
    "Ophrys druentica": "迪朗斯蜂兰",
    "Macrosyringion longiflorum": "长花丁香",
    "Pyracantha koidzumii": "小泉火棘",
    "Lactuca plumieri": "普拉米莴苣",
    "Aizoanthemum hispanicum": "西班牙阿兹藜花",
    "Phedimus aizoon": "费菜",
    "Phedimus spurius": "假费菜",
    "Nephrolepis cordifolia": "肾蕨",
    "Cereus jamacaru": "牙买加冲天柱",
    "Sedum pachyphyllum": "厚叶景天",
    "Sedum dendroideum": "树状景天",
    "Liriodendron chinensis": "鹅掌楸",
    "Atocion rupestre": "岩生阿托雪轮",
    "Tagetes tenuifolia": "细叶万寿菊",
    "Aegopodium podagraria": "羊角芹",
    "Acacia melanoxylon": "黑木金合欢",
    "Acacia saligna": "柳叶金合欢",
    "Patzkea paniculata": "圆锥帕茨草",
    "Perovskia abrotanoides": "青蒿叶分药花",
    "Ophrys occidentalis": "西方蜂兰",
    "Erechtites hieraciifolius": "菊芹",
    "Cenchrus longisetus": "长毛蒺藜草",
    "Nothofagus obliqua": "歪叶南山毛榉",
    "Calendula arvensis": "野金盏花",
    "Carthamus carduncellus": "刺苞红花",
    "Carthamus mitissimus": "极柔红花",
    "Chaerophyllum aureum": "金细叶芹",
    "Chaerophyllum hirsutum": "毛细叶芹",
    "Chaerophyllum villarsii": "维拉细叶芹",
    "Cirsium alsophilum": "林蓟",
    "Cirsium canum": "灰蓟",
    "Cirsium dissectum": "深裂蓟",
    "Cirsium eriophorum": "毛头蓟",
    "Cirsium erisithales": "黄蓟",
    "Cirsium ferox": "凶蓟",
    "Cirsium filipendulum": "线梗蓟",
    "Cirsium glabrum": "光蓟",
    "Cirsium heterophyllum": "异叶蓟",
    "Cirsium morisianum": "莫里西蓟",
    "Cirsium oleraceum": "菜蓟",
    "Cirsium rivulare": "溪蓟",
    "Cirsium tuberosum": "块茎蓟",
    "Collomia grandiflora": "大花科罗花",
    "Cucurbita maxima": "笋瓜",
    "Cymbalaria aequitriloba": "等三裂蔓柳穿鱼",
    "Cymbalaria hepaticifolia": "苔叶蔓柳穿鱼",
    "Cytinus hypocistis": "岩蔷薇寄生花",
    "Cytinus ruber": "红寄生花",
    "Daphne alpina": "高山瑞香",
    "Daphne cneorum": "玫瑰瑞香",
    "Daphne mezereum": "二月瑞香",
    "Daphne striata": "条纹瑞香",
    "Dorotheanthus bellidiformis": "彩虹菊",
    "Dryas octopetala": "仙女木",
    "Dryopteris carthusiana": "刺鳞毛蕨",
    "Dryopteris cristata": "冠鳞毛蕨",
    "Dryopteris dilatata": "宽鳞毛蕨",
    "Dryopteris expansa": "扩展鳞毛蕨",
    "Dryopteris villarii": "维拉鳞毛蕨",
    "Empetrum nigrum": "黑果岩高兰",
    "Epipactis atrorubens": "暗红火烧兰",
    "Epipactis leptochila": "细唇火烧兰",
    "Epipactis microphylla": "小叶火烧兰",
    "Epipactis muelleri": "米勒火烧兰",
    "Epipactis palustris": "沼泽火烧兰",
    "Epipactis phyllanthes": "叶花火烧兰",
    "Epipactis purpurata": "紫火烧兰",
    "Erucastrum gallicum": "法国芝麻菜",
    "Erucastrum incanum": "灰芝麻菜",
    "Erucastrum nasturtiifolium": "水田芥叶芝麻菜",
    "Fedia graciliflora": "细花败酱",
    "Fragaria moschata": "麝香草莓",
    "Freesia x hybrida": "杂交香雪兰",
    "Galega orientalis": "东方山羊豆",
    "Alliaria petiolata": "葱芥",
    "Geropogon hybridus": "杂种老翁须",
    "Gomphocarpus fruticosus": "灌状钉头果",
    "Gomphocarpus physocarpus": "气球钉头果",
    "Guizotia abyssinica": "油菊",
    "Hebe andersonii": "安德森赫柏",
    "Hebe brachysiphon": "短管赫柏",
    "Hebe ochracea": "赭色赫柏",
    "Hebe salicifolia": "柳叶赫柏",
    "Helicodiceros muscivorus": "蝇食魔芋",
    "Hippophae rhamnoides": "沙棘",
    "Hypericum calycinum": "大萼金丝桃",
    "Hypericum coris": "科西嘉金丝桃",
    "Hypericum elodes": "沼泽金丝桃",
    "Hypericum x inodorum": "无臭金丝桃",
    "Hypericum maculatum": "斑点金丝桃",
    "Hypericum nummularium": "铜钱叶金丝桃",
    "Hypericum pulchrum": "美丽金丝桃",
    "Hypericum richeri": "里歇金丝桃",
    "Dierama pulcherrimum": "天使钓竿",
    "Iva xanthiifolia": "假苍耳",
    "Kniphofia uvaria": "火炬花",
    "Lactuca alpina": "高山莴苣",
    "Lactuca macrophylla": "大叶莴苣",
    "Lactuca viminea": "柳枝莴苣",
    "Lamium album": "白花野芝麻",
    "Lamium maculatum": "斑点野芝麻",
    "Lathraea clandestina": "隐齿鳞草",
    "Lathraea squamaria": "齿鳞草",
    "Lavandula x intermedia": "杂薰衣草",
    "Lavandula latifolia": "宽叶薰衣草",
    "Limnanthes douglasii": "道格拉斯沼花",
    "Liriodendron tulipifera": "北美鹅掌楸",
    "Lupinus arboreus": "木羽扇豆",
    "Lupinus x regalis": "华丽羽扇豆",
    "Maianthemum bifolium": "舞鹤草",
    "Melilotus altissimus": "高草木樨",
    "Melilotus officinalis": "黄香草木樨",
    "Melilotus spicatus": "穗状草木樨",
    "Mercurialis ambigua": "疑山靛",
    "Mercurialis tomentosa": "毛山靛",
    "Moehringia ciliata": "缘毛种阜草",
    "Moehringia muscosa": "苔状种阜草",
    "Moehringia pentandra": "五蕊种阜草",
    "Narthecium ossifragum": "纳茜菜",
    "Neotinea lactea": "乳白新蒂兰",
    "Neotinea ustulata": "焦新蒂兰",
    "Noccaea caerulescens": "天蓝菥蓂",
    "Noccaea montana": "山地菥蓂",
    "Noccaea rotundifolia": "圆叶菥蓂",
    "Nymphaea candida": "雪白睡莲",
    "Nymphoides peltata": "荇菜",
    "Ophrys arachnitiformis": "蛛形蜂兰",
    "Ophrys aranifera": "蛛蜂兰",
    "Ophrys aveyronensis": "阿韦龙蜂兰",
    "Ophrys aymoninii": "艾莫宁蜂兰",
    "Ophrys bertolonii": "伯托洛尼蜂兰",
    "Ophrys catalaunica": "加泰罗尼亚蜂兰",
    "Ophrys exaltata": "高举蜂兰",
    "Ophrys fuciflora": "熊蜂蜂兰",
    "Ophrys incubacea": "暗蜂兰",
    "Ophrys lupercalis": "牧神蜂兰",
    "Ophrys morisii": "莫里斯蜂兰",
    "Ophrys passionis": "受难蜂兰",
    "Ophrys provincialis": "普罗旺斯蜂兰",
    "Ophrys saratoi": "萨拉托蜂兰",
    "Ophrys sulcata": "沟蜂兰",
    "Oreopteris limbosperma": "山羽蕨",
    "Anemone x hybrida": "杂交银莲花",
    "Anemone alpina": "高山银莲花",
    "Pancratium illyricum": "伊利里亚全能花",
    "Anemone apennina": "亚平宁银莲花",
    "Anemone baldensis": "巴尔多银莲花",
    "Papaver alpinum": "高山罂粟",
    "Papaver croceum": "橙黄罂粟",
    "Papaver orientale": "东方罂粟",
    "Papaver pseudoorientale": "假东方罂粟",
    "Papaver rhaeticum": "雷蒂亚罂粟",
    "Anemone halleri": "哈勒银莲花",
    "Anemone hepatica": "獐耳细辛",
    "Pelargonium x hybridum": "杂交天竺葵",
    "Pelargonium inquinans": "蹄纹天竺葵",
    "Pelargonium peltatum": "盾叶天竺葵",
    "Anemone montana": "山地银莲花",
    "Anemone nemorosa": "丛林银莲花",
    "Anemone pulsatilla": "白头翁",
    "Anemone rubra": "红银莲花",
    "Phedimus stellatus": "星状费菜",
    "Anemone sylvestris": "林生银莲花",
    "Anemone trifolia": "三叶银莲花",
    "Anemone vernalis": "春银莲花",
    "Angelica heterocarpa": "异果当归",
    "Angelica razulii": "拉祖当归",
    "Angelica sylvestris": "林当归",
    "Pleurospermum austriacum": "奥地利棱子芹",
    "Sasa palmata": "掌叶赤竹",
    "Anthericum ramosum": "分枝鸡尾兰",
    "Pyracantha coccinea": "欧洲火棘",
    "Pyracantha rogersiana": "罗杰斯火棘",
    "Holodiscus discolor": "异色全盘花",
    "Sagittaria graminea": "禾叶慈姑",
    "Sagittaria latifolia": "宽叶慈姑",
    "Sagittaria sagittifolia": "慈姑",
    "Diascia rigescens": "硬双距花",
    "Diascia vigilis": "活跃双距花",
    "Sedum sarmentosum": "垂盆草",
    "Sedum alpestre": "亚高山景天",
    "Sedum annuum": "一年生景天",
    "Sedum kamtschaticum": "勘察加景天",
    "Sedum mexicanum": "墨西哥景天",
    "Sedum ochroleucum": "淡黄景天",
    "Sedum sexangulare": "六棱景天",
    "Metasequoia glyptostroboides": "水杉",
    "Telekia speciosa": "特勒菊",
    "Thesium alpinum": "高山百蕊草",
    "Thesium linophyllon": "亚麻叶百蕊草",
    "Tradescantia x andersoniana": "安德森紫露草",
    "Tradescantia virginiana": "弗吉尼亚紫露草",
    "Trifolium alpestre": "近高山三叶草",
    "Trifolium alpinum": "高山三叶草",
    "Trifolium pallescens": "苍白三叶草",
    "Trifolium spadiceum": "栗色三叶草",
    "Trifolium thalii": "塔利三叶草",
    "Viscaria alpina": "高山黏蝇草",
    "Viscaria vulgaris": "普通黏蝇草",
    "Anemone hupehensis": "湖北银莲花",
    "Anemone vitifolia": "葡萄叶银莲花",
    "Adenostyles alpina": "高山腺柱菊",
    "Alcea biennis": "二年生蜀葵",
    "Anemone narcissiflora": "水仙银莲花",
    "Anemone ranunculoides": "毛茛状银莲花",
    "Angelica archangelica": "圆叶当归",
    "Chaerophyllum bulbosum": "块茎细叶芹",
    "Cirsium acaulon": "无茎蓟",
    "Cirsium spinosissimum": "极刺蓟",
    "Cymbalaria muralis": "蔓柳穿鱼",
    "Eritrichium nanum": "矮齿缘草",
    "Fragaria viridis": "绿草莓",
    "Honckenya peploides": "冰岛滨藜草",
    "Hypericum hyssopifolium": "海索草叶金丝桃",
    "Hypericum mutilum": "短小金丝桃",
    "Lactuca perennis": "宿根莴苣",
    "Sedum atratum": "暗色景天",
    "Thesium pyrenaicum": "比利牛斯百蕊草",
    "Trifolium medium": "中间三叶草",
    "Trinia glauca": "粉绿三叶芹",
    "Sedum montanum": "山地景天",
    "Trifolium badium": "褐三叶草",
    "Freesia refracta": "香雪兰",
    "Freesia alba": "白香雪兰",
    "Cobaea scandens": "电灯花",
    "Fragaria virginiana": "弗吉尼亚草莓",
    "Anemone pratensis": "草原银莲花",
    "Sagittaria lancifolia": "披针叶慈姑",
    "Neotinea tridentata": "三齿新蒂兰",
    "Adenostyles alliariae": "葱芥叶腺柱菊",
    "Ophrys pseudoscolopax": "假鹬蜂兰",
    "Sedum palmeri": "帕默景天",
    "Hypericum olympicum": "奥林匹斯金丝桃",
    "Tradescantia zebrina": "吊竹梅",
    "Dryopteris erythrosora": "红囊鳞毛蕨",
    "Adenostyles leucophylla": "白叶腺柱菊",
    "Calycanthus floridus": "美国腊梅",
    "Phyllanthus niruri": "珠子草",
    "Ophrys araneola": "小蛛蜂兰",
    "Anemone blanda": "希腊银莲花",
    "Aralia elata": "辽东楤木",
    "Ophrys virescens": "变绿蜂兰",
    "Clethra alnifolia": "桤叶山柳",
    "Corispermum pallasii": "帕拉斯虫实",
    "Hypericum patulum": "金丝梅",
    "Hypericum x hidcoteense": "希德科特金丝桃",
    "Lupinus nootkatensis": "努特卡羽扇豆",
    "Smilax rotundifolia": "圆叶菝葜",
    "Perovskia atriplicifolia": "滨藜叶分药花",
    "Nothofagus antarctica": "南极南山毛榉",
    "Iva annua": "一年假苍耳",
    "Dryopteris fragrans": "香鳞毛蕨",
    "Neotinea conica": "锥形新蒂兰",
    "Tetraclinis articulata": "非洲柏",
    "Alcea setosa": "刚毛蜀葵",
    "Chaerophyllum aromaticum": "芳香细叶芹",
    "Cucurbita moschata": "南瓜",
    "Daphne sericea": "绢毛瑞香",
    "Lamium orvala": "大花野芝麻",
    "Paederota bonarota": "博纳罗塔爬地桐",
    "Rhodothamnus chamaecistus": "矮岩须",
    "Ophrys lunulata": "新月蜂兰",
    "Schefflera actinophylla": "辐叶鹅掌柴",
    "Astydamia latifolia": "宽叶海岛芹",
    "Lavandula pinnata": "羽叶薰衣草",
    "Angelica atropurpurea": "暗紫当归",
    "Acacia pravissima": "极弯金合欢",
    "Adonis pyrenaica": "比利牛斯侧金盏花",
    "Adonis vernalis": "春侧金盏花",
    "Barbarea rupicola": "岩生山芥",
    "Barbarea vulgaris": "山芥",
    "Acacia baileyana": "贝利金合欢",
    "Bellium bellidioides": "雏菊状小钟花",
    "Bocoa prouacensis": "普罗阿卡博可豆",
    "Nephrolepis biserrata": "双锯肾蕨",
    "Vanilla pompona": "蓬蓬香荚兰",
    "Guatteria anteridifera": "花药瓜泰花",
    "Caraipa densifolia": "密叶卡拉木",
    "Caraipa punctulata": "斑卡拉木",
    "Vismia cayennensis": "卡宴维氏木",
    "Vismia macrophylla": "大叶维氏木",
    "Vismia sessilifolia": "无柄叶维氏木",
    "Dryopteris wallichiana": "瓦氏鳞毛蕨",
    "Xylopia frutescens": "灌状木瓣树",
    "Xylopia nitida": "光亮木瓣树",
    "Xylopia sericea": "绢毛木瓣树",
    "Phyllanthus urinaria": "叶下珠",
    "Pogonophora schomburgkiana": "顺布须木",
    "Sagotia racemosa": "总序萨果戟",
    "Bonafousia undulata": "波叶好君花",
    "Guarea gomma": "胶格瓦楝",
    "Nymphoides indica": "金银莲花",
    "Anthurium hookeri": "胡克花烛",
    "Anthurium jenmanii": "詹曼花烛",
    "Anthurium scandens": "攀援花烛",
    "Dracontium polyphyllum": "多叶龙莲",
    "Crotalaria retusa": "凹叶猪屎豆",
    "Peperomia magnoliifolia": "木兰叶椒草",
    "Peperomia obtusifolia": "圆叶椒草",
    "Peperomia quadrangularis": "棱茎椒草",
    "Peperomia rotundifolia": "圆叶蔓椒草",
    "Peperomia serpens": "匍匐椒草",
    "Declieuxia fruticosa": "灌状德克木",
    "Mauritia flexuosa": "曲叶毛瑞榈",
    "Urera baccifera": "浆果刺痒藤",
    "Pereskia bleo": "玫瑰麒麟",
    "Cereus hexagonus": "六角冲天柱",
    "Xylopia crinita": "毛木瓣树",
    "Vanilla planifolia": "香荚兰",
    "Aciotis rubricaulis": "红茎耳药草",
    "Guatteria amplifolia": "大叶瓜泰花",
    "Luffa cylindrica": "丝瓜",
    "Cryptostegia madagascariensis": "马达加斯加橡胶藤",
    "Schefflera decaphylla": "十叶鹅掌柴",
    "Aphelandra scabra": "粗糙单药花",
    "Asystasia gangetica": "宽叶十万错",
    "Piriqueta cistoides": "半日花拟皮草",
    "Acalypha wilkesiana": "红桑",
    "Breynia disticha": "彩叶黑面神",
    "Crotalaria incana": "灰毛猪屎豆",
    "Crotalaria pallida": "猪屎豆",
    "Kigelia africana": "吊灯树",
    "Guatteria citriodora": "柠檬香瓜泰花",
    "Acalypha indica": "印度铁苋菜",
    "Guatteria punctata": "斑点瓜泰花",
    "Anthurium crystallinum": "水晶花烛",
    "Cryptopus elatus": "高隐足兰",
    "Cryptostegia grandiflora": "大花橡胶藤",
    "Eranthemum pulchellum": "可爱花",
    "Alocasia cucullata": "尖尾芋",
    "Alocasia longiloba": "长裂海芋",
    "Alocasia macrorrhizos": "海芋",
    "Faujasia salicifolia": "柳叶福特菊",
    "Fernelia buxifolia": "黄杨叶弗内木",
    "Fragaria x ananassa": "草莓",
    "Geniostoma borbonicum": "波旁髯喉花",
    "Hernandia mascarenensis": "马斯卡林莲叶桐",
    "Hypericum lanceolatum": "披针叶金丝桃",
    "Acacia auriculiformis": "大叶金合欢",
    "Leonitis nepetifolia": "荆芥叶狮耳花",
    "Mussaenda arcuata": "弓形玉叶金花",
    "Nephrolepis abrupta": "截形肾蕨",
    "Acacia heterophylla": "异叶金合欢",
    "Paederia foetida": "鸡屎藤",
    "Pelargonium x asperum": "粗糙天竺葵",
    "Pereskia grandifolia": "大叶木麒麟",
    "Antirhea borbonica": "波旁对蕊木",
    "Phyllanthus emblica": "余甘子",
    "Phyllanthus niruroides": "珠草状叶下珠",
    "Phyllanthus phillyreifolius": "菲利桂叶叶下珠",
    "Pongamia pinnata": "水黄皮",
    "Acacia podalyriifolia": "珍珠金合欢",
    "Schefflera actinophylla": "辐叶鹅掌柴",
    "Acalypha hispida": "红穗铁苋菜",
    "Acalypha integrifolia": "全缘叶铁苋菜",
    "Stemodia verticillata": "轮生茎花",
    "Stoebe passerinoides": "瑞香状斯托菊",
    "Strongylodon macrobotrys": "碧玉藤",
    "Tradescantia pallida": "紫竹梅",
    "Trimezia martinicensis": "马提尼克三鸢尾",
    "Vangueria madagascariensis": "马达加斯加范果树",
    "Vepris lanceolata": "披针叶维普木",
    "Zaleya pentandra": "五蕊扎利草",
    "Cereus repandus": "波纹冲天柱",
    "Bismarckia nobilis": "霸王棕",
    "Acacia nilotica": "阿拉伯金合欢",
    "Schefflera arboricola": "鹅掌藤",
    "Fragaria chiloensis": "智利草莓",
    "Aphelandra squarrosa": "斑叶单药花",
    "Gynura aurantiaca": "橙花三七草",
    "Pereskia aculeata": "木麒麟",
    "Peperomia argyreia": "西瓜皮椒草",
    "Peperomia caperata": "皱叶椒草",
    "Peperomia obtusifolia": "圆叶椒草",
    "Anthurium andraeanum": "红掌",
    "Anthurium scherzerianum": "火鹤花",
    "Zamia furfuracea": "鳞秕泽米铁",
    "Dendrobium nobile": "石斛",
    "Nandina domestica": "南天竹",
    "Nymphaea nouchali": "延药睡莲",
    "Falcataria moluccana": "南洋楹",
    "Acacia tortuosa": "扭曲金合欢",
    "Bourreria succulenta": "多汁博雷木",
    "Crotalaria brevidens": "短齿猪屎豆",
    "Crotalaria pumila": "矮猪屎豆",
    "Dendrobium chrysotoxum": "鼓槌石斛",
    "Dendrobium crumenatum": "禾叶石斛",
    "Dendrobium moschatum": "麝香石斛",
    "Entada gigas": "巨榼藤",
    "Fittonia albivenis": "白脉网纹草",
    "Illicium verum": "八角",
    "Lactuca floridana": "佛罗里达莴苣",
    "Mussaenda pubescens": "玉叶金花",
    "Neolamarckia cadamba": "团花",
    "Nymphaea ampla": "宽睡莲",
    "Phyllanthus epiphyllanthus": "叶上叶下珠",
    "Phyllanthus mimosoides": "含羞草叶叶下珠",
    "Pilosocereus royeni": "罗延毛柱",
    "Selenicereus anthonyanus": "鱼骨蛇鞭柱",
    "Selenicereus grandiflorus": "大花蛇鞭柱",
    "Zamia pumila": "矮泽米铁",
    "Acalypha aristata": "芒铁苋菜",
    "Chamerion latifolium": "宽叶柳兰",
    "Cirsium discolor": "异色蓟",
    "Cirsium foliosum": "多叶蓟",
    "Cirsium muticum": "钝蓟",
    "Cirsium undulatum": "波叶蓟",
    "Comptonia peregrina": "香蕨木",
    "Conoclinium coelestinum": "蓝雾花",
    "Dalea purpurea": "紫戴尔豆",
    "Daucus pusillus": "小胡萝卜",
    "Diervilla lonicera": "忍冬叶黄锦带",
    "Dryopteris carthusiana": "刺鳞毛蕨",
    "Dryopteris cristata": "冠鳞毛蕨",
    "Dryopteris intermedia": "中间鳞毛蕨",
    "Dryopteris marginalis": "缘鳞毛蕨",
    "Duchesnea indica": "蛇莓",
    "Epipactis gigantea": "巨火烧兰",
    "Hypericum kalmianum": "卡尔姆金丝桃",
    "Hypericum prolificum": "多花金丝桃",
    "Hypericum punctatum": "斑点金丝桃",
    "Anemone canadensis": "加拿大银莲花",
    "Iva frutescens": "灌状假苍耳",
    "Anemone multifida": "多裂银莲花",
    "Anemone virginiana": "弗吉尼亚银莲花",
    "Lactuca biennis": "二年生莴苣",
    "Lactuca canadensis": "加拿大莴苣",
    "Lamium maculatum": "斑点野芝麻",
    "Leersia virginica": "弗吉尼亚李氏禾",
    "Angelica lucida": "光泽当归",
    "Lupinus argenteus": "银羽扇豆",
    "Lupinus bicolor": "双色羽扇豆",
    "Maianthemum canadense": "加拿大舞鹤草",
    "Maianthemum racemosum": "总状舞鹤草",
    "Maianthemum stellatum": "星舞鹤草",
    "Maianthemum trifolium": "三叶舞鹤草",
    "Mertensia maritima": "海滨滨瓣庆",
    "Mertensia paniculata": "圆锥滨瓣庆",
    "Mertensia virginica": "弗吉尼亚滨瓣庆",
    "Mitella diphylla": "二叶唢呐草",
    "Moehringia lateriflora": "侧花种阜草",
    "Nymphaea mexicana": "墨西哥睡莲",
    "Nymphaea odorata": "香睡莲",
    "Nymphaea tetragona": "睡莲",
    "Osmunda cinnamomea": "桂皮紫萁",
    "Osmunda claytoniana": "绒紫萁",
    "Papaver nudicaule": "冰岛罂粟",
    "Aralia hispida": "硬毛楤木",
    "Aralia nudicaulis": "裸茎楤木",
    "Aralia racemosa": "总序楤木",
    "Pyracantha coccinea": "欧洲火棘",
    "Sedum divergens": "叉开景天",
    "Sedum lanceolatum": "披针叶景天",
    "Sedum oreganum": "俄勒冈景天",
    "Sedum spathulifolium": "匙叶景天",
    "Sedum ternatum": "三叶景天",
    "Smilax herbacea": "草菝葜",
    "Smilax tamnoides": "假菝葜",
    "Tradescantia occidentalis": "西方紫露草",
    "Tradescantia ohiensis": "俄亥俄紫露草",
    "Balsamorhiza sagittata": "箭叶香根菊",
    "Barbarea orthoceras": "直果山芥",
    "Barbarea vulgaris": "山芥",
    "Calochortus macrocarpus": "大果蝴蝶百合",
    "Entada phaseoloides": "榼藤",
    "Cerbera manghas": "海杧果",
    "Hernandia cordigera": "心叶莲叶桐",
    "Acacia simplex": "单叶金合欢",
    "Dubouzetia confusa": "混淆杜布木",
    "Dubouzetia campanulata": "钟状杜布木",
    "Acacia spirorbis": "旋荚金合欢",
    "Atractocarpus platyxylon": "宽木箭果木",
    "Nepenthes vieillardii": "维耶猪笼草",
    "Dendrobium closterium": "棒状石斛",
    "Dracophyllum verticillatum": "轮生龙叶树",
    "Schefflera spp.": "鹅掌柴",
    "Tagetes lucida": "亮叶万寿菊",
    "Anisocampium niponicum": "日本蹄盖蕨",
    "Mertensia ciliata": "缘毛滨瓣庆",
    "Lithops fulviceps": "褐头生石花",
    "Lithops karasmontana": "卡拉生石花",
    "Lithops marmorata": "大理石生石花",
    "Lithops pseudotruncatella": "曲玉",
    "Fittonia albivenis": "白脉网纹草",
    "Lithops spp.": "生石花",
    "Cereus hildmannianus": "希尔曼冲天柱",
    "Neobuxbaumia polylopha": "多棱新布氏仙人掌",
    "Calycanthus occidentalis": "西方腊梅",
    "Tradescantia subaspera": "粗紫露草",
    "Sedum kamtschaticum": "勘察加景天",
    "Sedum lineare": "佛甲草",
    "Sedum morganianum": "玉珠帘",
    "Cucurbita foetidissima": "臭瓜",
    "Eucryphia cordifolia": "心叶尤克木",
    "Dryopteris cycadina": "苏铁鳞毛蕨",
    "Dryopteris erythrosora": "红囊鳞毛蕨",
    "Dryopteris sieboldii": "西博德鳞毛蕨",
    "Rumohra adiantiformis": "铁线蕨叶骨碎补",
    "Oxydendrum arboreum": "酸模树",
    "Lupinus albifrons": "白叶羽扇豆",
    "Lycoris radiata": "石蒜",
    "Garrya elliptica": "椭圆加里亚",
    "Lycoris squamigera": "鹿葱",
    "Pelargonium crispum": "皱叶天竺葵",
    "Pelargonium x hortorum": "园艺天竺葵",
    "Loropetalum chinense": "继木",
    "Hypericum frondosum": "多叶金丝桃",
    "Liriope muscari": "阔叶山麦冬",
    "Limnanthes douglasii": "道格拉斯沼花",
    "Nothofagus alpina": "高山南山毛榉",
    "Nothofagus pumilio": "矮南山毛榉",
    "Abeliophyllum distichum": "朝鲜白连翘",
    "Dendrobium aphyllum": "落叶石斛",
    "Dendrobium spp.": "石斛",
    "Vanilla planifolia": "香荚兰",
    "Heteromorpha arborescens": "树状异形木",
    "Lapageria rosea": "智利风铃花",
    "Peperomia argyreia": "西瓜皮椒草",
    "Peperomia dolabriformis": "斧叶椒草",
    "Hebe franciscana": "旧金山赫柏",
    "Maurandya barclayana": "巴克莱蔓柳",
    "Sasa palmata": "掌叶赤竹",
    "Anemone patens": "白头翁",
    "Fragaria virginiana": "弗吉尼亚草莓",
    "Fragaria x ananassa": "草莓",
    "Mussaenda philippica": "菲律宾玉叶金花",
    "Limonia acidissima": "木苹果",
    "Illicium floridanum": "佛罗里达八角",
    "Browallia speciosa": "美丽布罗瓦花",
    "Alocasia cuprea": "铜色海芋",
    "Alocasia micholitziana": "美氏海芋",
    "Alocasia odora": "海芋",
    "Daphne odora": "瑞香",
    "Alocasia sanderiana": "桑德海芋",
    "Daphne tangutica": "甘肃瑞香",
    "Kniphofia uvaria": "火炬花",
    "Zamia furfuracea": "鳞秕泽米铁",
    "Guaiacum sanctum": "神圣愈疮木",
    "Nepenthes spp.": "猪笼草",
    "Pelargonium spp.": "天竺葵",
    "Pancratium maritimum": "海滩全能花",
    "Sedum palmeri": "帕默景天",
    "Aphelandra sinclairiana": "辛克莱单药花",
    "Alocasia macrorrhizos": "海芋",
    "Acacia confusa": "相思树",
    "Acacia koaia": "科阿金合欢",
    "Nephrolepis falcata": "镰叶肾蕨",
    "Tradescantia zebrina": "吊竹梅",
    "Calodendrum capense": "好望角美树",
    "Pelargonium grandiflorum": "大花天竺葵",
    "Hypericum revolutum": "反卷金丝桃",
    "Schkuhria pinnata": "羽状史库菊",
    "Maytenus boaria": "智利美登木",
    "Melampodium perfoliatum": "贯叶黑足菊",
    "Hernandia nymphaeifolia": "睡莲叶莲叶桐",
    "Mazus pumilus": "通泉草",
    "Melampodium divaricatum": "叉开黑足菊",
    "Breynia vitis-idaea": "越橘叶黑面神",
    "Prosopis farcta": "实牧豆树",
    "Acacia farnesiana": "金合欢",
    "Freycinetia cumingiana": "卡明藤露兜",
    "Crotalaria laburnifolia": "金链花叶猪屎豆",
    "Dalbergia sissoo": "印度黄檀",
    "Dischidia nummularia": "圆叶眼树莲",
    "Schefflera heptaphylla": "七叶鹅掌柴",
    "Schinopsis balansae": "红破斧木",
    "Smilax china": "菝葜",
    "Barringtonia acutangula": "锐棱棋盘脚",
    "Maerua triphylla": "三叶梅鲁木",
    "Asystasia mysorensis": "迈索尔十万错",
    "Lactuca virosa": "毒莴苣",
    "Calendula arvensis": "野金盏花",
    "Herbertia lahue": "拉胡小鸢尾",
    "Hypericum hypericoides": "金丝桃状金丝桃",
    "Hypericum tetrapetalum": "四瓣金丝桃",
    "Keckiella cordifolia": "心叶凯克花",
    "Liriope muscari": "阔叶山麦冬",
    "Lupinus chamissonis": "沙米索羽扇豆",
    "Lupinus diffusus": "铺散羽扇豆",
    "Lupinus formosus": "美丽羽扇豆",
    "Lupinus hirsutissimus": "极毛羽扇豆",
    "Lupinus subcarnosus": "亚肉色羽扇豆",
    "Lupinus texensis": "德克萨斯羽扇豆",
    "Lyonothamnus floribundus": "多花铁木",
    "Mazus pumilus": "通泉草",
    "Melampodium leucanthum": "白花黑足菊",
    "Metasequoia glyptostroboides": "水杉",
    "Aralia californica": "加州楤木",
    "Nyctaginia capitata": "头状夜香草",
    "Aralia spinosa": "刺楤木",
    "Pelargonium panduriforme": "提琴形天竺葵",
    "Pelargonium zonale": "马蹄纹天竺葵",
    "Prosopis glandulosa": "腺牧豆树",
    "Prosopis pubescens": "柔毛牧豆树",
    "Sagittaria montevidensis": "蒙得维的亚慈姑",
    "Sedum albomarginatum": "白边景天",
    "Sedum glaucophyllum": "粉绿叶景天",
    "Sedum laxum": "疏景天",
    "Sedum moranense": "莫拉景天",
    "Sedum niveum": "雪白景天",
    "Sedum obtusatum": "钝景天",
    "Sedum pulchellum": "美丽景天",
    "Smilax bona-nox": "博纳菝葜",
    "Smilax glauca": "粉绿菝葜",
    "Smilax laurifolia": "桂叶菝葜",
    "Stanleya pinnata": "羽状斯坦利芥",
    "Tagetes lemmonii": "莱蒙万寿菊",
    "Tradescantia crassifolia": "厚叶紫露草",
    "Xylococcus bicolor": "双色木浆果",
    "Brodiaea elegans": "雅致布罗地花",
    "Calochortus eurycarpus": "宽果蝴蝶百合",
    "Calochortus gunnisonii": "甘尼森蝴蝶百合",
    "Calochortus leichtlinii": "莱希特林蝴蝶百合",
    "Calochortus luteus": "黄花蝴蝶百合",
    "Calochortus splendens": "华丽蝴蝶百合",
    "Calochortus tolmiei": "托尔米蝴蝶百合",
    "Calylophus hartwegii": "哈特韦格萼花",
    "Chaerophyllum tainturieri": "坦蒂里耶细叶芹",
    "Cirsium altissimum": "极高蓟",
    "Cirsium horridulum": "恐怖蓟",
    "Cirsium texanum": "德克萨斯蓟",
    "Diervilla sessilifolia": "无柄叶黄锦带",
    "Acacia berlandieri": "伯兰德金合欢",
    "Elephantopus elatus": "高地地胆草",
    "Alocasia cucullata": "尖尾芋",
    "Acacia redolens": "芳香金合欢",
    "Acacia rigidula": "硬金合欢",
    "Hackelia velutina": "绒毛假鹤虱",
    "Haplophyton crooksii": "克鲁克单叶藤",
    "Aextoxicon punctatum": "斑叶毒鼠子",
    "Lithops aucampiae": "奥坎生石花",
    "Lithops olivacea": "橄榄玉",
    "Cyrtanthus elatus": "高贵曲花",
    "Guatteria aeruginosa": "铜绿瓜泰花",
    "Dischidia ovata": "卵叶眼树莲",
    "Trachelospermum asiaticum": "亚洲络石",
    "Alocasia baginda": "巴金达海芋",
    "Alocasia lauterbachiana": "劳特巴赫海芋",
    "Alocasia reginula": "小女王海芋",
    "Alocasia wentii": "温特海芋",
    "Alocasia zebrina": "斑马海芋",
    "Anthurium clarinervium": "明脉花烛",
    "Anthurium faustomirandae": "福斯特花烛",
    "Anthurium salvinii": "萨尔文花烛",
    "Anthurium schlechtendalii": "施氏花烛",
    "Anthurium veitchii": "维奇花烛",
    "Anthurium warocqueanum": "女王花烛",
    "Wodyetia bifurcata": "狐尾椰",
    "Cereus forbesii": "福布斯冲天柱",
    "Cereus uruguayanus": "乌拉圭冲天柱",
    "Coryphantha elephantidens": "象牙丸",
    "Pilosocereus chrysostele": "金柱毛柱",
    "Pilosocereus pachycladus": "粗枝毛柱",
    "Selenicereus anthonyanus": "鱼骨蛇鞭柱",
    "Stenocactus multicostatus": "多棱球",
    "Tephrocactus geometricus": "几何灰球掌",
    "Pterocephalus perennis": "宿根翼首花",
    "Maytenus ilicifolia": "冬青叶美登木",
    "Cyanotis somaliensis": "索马里蓝耳草",
    "Tradescantia x andersoniana": "安德森紫露草",
    "Tradescantia sillamontana": "白雪姬",
    "Cirsium palustre": "沼泽蓟",
    "Erechtites minima": "矮菊芹",
    "Lactuca alpina": "高山莴苣",
    "Leptinella potentillina": "委陵菜小铜扣",
    "Leucophyta brownii": "布朗白菊",
    "Melampodium divaricatum": "叉开黑足菊",
    "Othonna capensis": "好望角奥索菊",
    "Rhodanthe chlorocephala": "绿头鳞苞菊",
    "Tagetes lemmonii": "莱蒙万寿菊",
    "Tagetes lunulata": "新月万寿菊",
    "Sedum adolphii": "阿道夫景天",
    "Sedum allantoides": "腊肠状景天",
    "Sedum burrito": "新玉缀",
    "Sedum clavatum": "玉缀",
    "Sedum compressum": "扁景天",
    "Sedum cyaneum": "蓝景天",
    "Sedum decumbens": "俯卧景天",
    "Sedum furfuraceum": "糠状景天",
    "Sedum hernandezii": "赫氏景天",
    "Sedum japonicum": "日本景天",
    "Sedum makinoi": "圆叶景天",
    "Sedum nussbaumerianum": "铭月",
    "Sedum praealtum": "灌木状景天",
    "Sedum rubrotinctum": "虹之玉",
    "Uncinia rubra": "红钩莎草",
    "Empetrum rubrum": "红果岩高兰",
    "Acalypha macrostachya": "大穗铁苋菜",
    "Pelargonium echinatum": "刺天竺葵",
    "Pelargonium x hortorum": "园艺天竺葵",
    "Pelargonium sidoides": "南非天竺葵",
    "Pelargonium tomentosum": "绒毛天竺葵",
    "Lavandula canariensis": "加那利薰衣草",
    "Acacia auriculiformis": "大叶金合欢",
    "Acacia brevispica": "短穗金合欢",
    "Acacia caven": "卡文金合欢",
    "Acacia cognata": "近缘金合欢",
    "Acacia confluens": "合流金合欢",
    "Acacia podalyriifolia": "珍珠金合欢",
    "Acacia saligna": "柳叶金合欢",
    "Dalbergia retusa": "微凹黄檀",
    "Lupinus nootkatensis": "努特卡羽扇豆",
    "Prosopis pallida": "苍白牧豆树",
    "Cedrela fissilis": "裂叶洋椿",
    "Nepenthes mirabilis": "奇异猪笼草",
    "Nepenthes x neglecta": "忽视猪笼草",
    "Nothofagus betuloides": "桦状南山毛榉",
    "Nothofagus dombeyi": "多贝南山毛榉",
    "Nothofagus nitida": "光亮南山毛榉",
    "Nymphaea rubra": "红睡莲",
    "Dendrobium anosmum": "檀香石斛",
    "Dendrobium kingianum": "金氏石斛",
    "Dendrobium munificum": "慷慨石斛",
    "Dendrobium thyrsiflorum": "球花石斛",
    "Dendrobium victoriae-reginae": "女王石斛",
    "Erycina pusilla": "矮小扇叶兰",
    "Adlumia fungosa": "蔓荷包藤",
    "Peperomia albovittata": "白脉椒草",
    "Peperomia clusiifolia": "克鲁西叶椒草",
    "Peperomia columella": "塔椒草",
    "Peperomia ferreyrae": "幸福豆椒草",
    "Peperomia graveolens": "烈香椒草",
    "Peperomia maculosa": "斑叶椒草",
    "Peperomia pecuniifolia": "钱叶椒草",
    "Peperomia polybotrya": "瀑布椒草",
    "Peperomia prostrata": "蔓椒草",
    "Peperomia tetragona": "四棱椒草",
    "Peperomia verticillata": "轮叶椒草",
    "Hebe andersonii": "安德森赫柏",
    "Lomatia ferruginea": "锈色洛马木",
    "Anemone pavoniana": "孔雀银莲花",
    "Anemone tomentosa": "绒毛银莲花",
    "Hepatica nobilis": "獐耳细辛",
    "Fragaria x ananassa": "草莓",
    "Margaritopsis haematocarpa": "血红果珍珠木",
    "Angostura granulosa": "颗粒安古树",
    "Smilax excelsa": "高大菝葜",
    "Coussapoa villosa": "毛库萨榕",
    "Cyphostemma cyphopetalum": "曲瓣葡瓮",
    "Cyphostemma juttae": "尤塔葡瓮",
    "Cyphostemma serpens": "匍匐葡瓮",
    "Nepenthes alata": "翼状猪笼草",
    "Nepenthes truncata": "截叶猪笼草",
    "Lavandula spp.": "薰衣草",
    "Cymbalaria muralis": "蔓柳穿鱼",
    "Aphelandra aurantiaca": "橙花单药花",
    "Guatteria dolichopoda": "长梗瓜泰花",
    "Stenanona costaricensis": "哥斯达黎加狭花",
    "Schefflera morototoni": "莫罗鹅掌柴",
    "Bourreria andrieuxii": "安德里厄博雷木",
    "Bourreria costaricensis": "哥斯达黎加博雷木",
    "Alibertia edulis": "可食阿利柏木",
    "Acacia senegalensis": "塞内加尔金合欢",
}


_GENUS_ZH = {
    "Acacia": "金合欢", "Acalypha": "铁苋菜", "Adonis": "侧金盏花",
    "Alcea": "蜀葵", "Alocasia": "海芋", "Althaea": "药蜀葵",
    "Anemone": "银莲花", "Angelica": "当归", "Anthurium": "花烛",
    "Aphelandra": "单药花", "Aralia": "楤木", "Aristea": "蓝星花",
    "Asystasia": "十万错", "Barbarea": "山芥", "Breynia": "黑面神",
    "Calendula": "金盏花", "Calochortus": "蝴蝶百合", "Carthamus": "红花",
    "Casuarina": "木麻黄", "Cenchrus": "蒺藜草", "Centranthus": "红缬草",
    "Cereus": "冲天柱", "Chaerophyllum": "细叶芹", "Cirsium": "蓟",
    "Cobaea": "电灯花", "Crotalaria": "猪屎豆", "Cryptostegia": "橡胶藤",
    "Cucurbita": "南瓜", "Cymbalaria": "蔓柳穿鱼", "Daphne": "瑞香",
    "Daucus": "胡萝卜", "Dendrobium": "石斛", "Dryopteris": "鳞毛蕨",
    "Duchesnea": "蛇莓", "Epipactis": "火烧兰", "Erechtites": "菊芹",
    "Fittonia": "网纹草", "Fragaria": "草莓", "Freesia": "香雪兰",
    "Galega": "山羊豆", "Gynura": "三七草", "Hebe": "赫柏",
    "Hypericum": "金丝桃", "Hyoscyamus": "天仙子", "Illicium": "八角",
    "Kniphofia": "火炬花", "Lactuca": "莴苣", "Lagenaria": "葫芦",
    "Lamium": "野芝麻", "Lavandula": "薰衣草", "Lithops": "生石花",
    "Luffa": "丝瓜", "Lupinus": "羽扇豆", "Maianthemum": "舞鹤草",
    "Melilotus": "草木樨", "Metasequoia": "水杉", "Mussaenda": "玉叶金花",
    "Nepenthes": "猪笼草", "Nephrolepis": "肾蕨", "Nothofagus": "南山毛榉",
    "Nymphaea": "睡莲", "Ophrys": "蜂兰", "Osmunda": "紫萁",
    "Pancratium": "全能花", "Papaver": "罂粟", "Pelargonium": "天竺葵",
    "Peperomia": "椒草", "Pereskia": "木麒麟", "Phyllanthus": "叶下珠",
    "Prosopis": "牧豆树", "Pyracantha": "火棘", "Schefflera": "鹅掌柴",
    "Sedum": "景天", "Smilax": "菝葜", "Tagetes": "万寿菊",
    "Thapsia": "毒胡萝卜", "Thesium": "百蕊草", "Tradescantia": "紫露草",
    "Trifolium": "三叶草", "Vanilla": "香荚兰", "Wodyetia": "狐尾椰",
    "Zamia": "泽米铁", "Zamioculcas": "金钱树",
}


def _translate_part(part):
    text = part.replace("_", " ")
    if text in _SPECIES_ZH:
        return _SPECIES_ZH[text]
    tokens = text.split()
    if not tokens:
        return text
    genus = tokens[0]
    if genus in _GENUS_ZH:
        return _GENUS_ZH[genus]
    return text


def translate_label(label):
    if not label:
        return label
    if label in _LABEL_ZH:
        return _LABEL_ZH[label]
    if "___" not in label:
        return _translate_part(label)
    plant_name, detail = label.split("___", 1)
    return f"{_translate_part(plant_name)} / {_translate_part(detail)}"


def clamp(value, low, high):
    return max(low, min(high, value))


def scale_box_to_original(box, ratio, padding, image_shape):
    x1, y1, x2, y2 = box
    pad_x, pad_y = padding
    height, width = image_shape[:2]

    x1 = int(round((x1 - pad_x) / ratio[0]))
    y1 = int(round((y1 - pad_y) / ratio[1]))
    x2 = int(round((x2 - pad_x) / ratio[0]))
    y2 = int(round((y2 - pad_y) / ratio[1]))

    x1 = clamp(x1, 0, width - 1)
    y1 = clamp(y1, 0, height - 1)
    x2 = clamp(x2, 0, width - 1)
    y2 = clamp(y2, 0, height - 1)

    if x2 < x1:
        x1, x2 = x2, x1
    if y2 < y1:
        y1, y2 = y2, y1

    return x1, y1, x2, y2


def build_top_candidates(class_probs, top_k=3):
    best_scores = np.max(class_probs, axis=0)
    top_indices = np.argsort(best_scores)[::-1][:top_k]
    candidates = []
    for index in top_indices:
        candidates.append(
            {
                "label": CLASSES[int(index)],
                "score": float(best_scores[index]),
                "class_id": int(index),
            }
        )
    return candidates


def build_detections(boxes, scores, classes, ratio, padding, image_shape):
    detections = []
    for box, score, class_id in zip(boxes, scores, classes):
        x1, y1, x2, y2 = scale_box_to_original(box, ratio, padding, image_shape)
        detections.append(
            {
                "label": CLASSES[int(class_id)],
                "score": float(score),
                "class_id": int(class_id),
                "box": (x1, y1, x2, y2),
            }
        )
    detections.sort(key=lambda item: item["score"], reverse=True)
    return detections


def nms_boxes(boxes, scores):
    x = boxes[:, 0]
    y = boxes[:, 1]
    w = boxes[:, 2] - boxes[:, 0]
    h = boxes[:, 3] - boxes[:, 1]

    areas = w * h
    order = scores.argsort()[::-1]

    keep = []
    while order.size > 0:
        i = order[0]
        keep.append(i)

        xx1 = np.maximum(x[i], x[order[1:]])
        yy1 = np.maximum(y[i], y[order[1:]])
        xx2 = np.minimum(x[i] + w[i], x[order[1:]] + w[order[1:]])
        yy2 = np.minimum(y[i] + h[i], y[order[1:]] + h[order[1:]])

        w1 = np.maximum(0.0, xx2 - xx1 + 0.00001)
        h1 = np.maximum(0.0, yy2 - yy1 + 0.00001)
        inter = w1 * h1

        ovr = inter / (areas[i] + areas[order[1:]] - inter)
        inds = np.where(ovr <= NMS_THRESH)[0]
        order = order[inds + 1]
    return np.array(keep)


def yolov8_post_process(input_data):
    if len(input_data) != 1:
        print(f"警告: 期望1个输出，实际得到{len(input_data)}个")
        return None, None, None, []

    output = input_data[0].transpose(0, 2, 1)
    bbox = output[0, :, :4]
    class_probs = output[0, :, 4:]
    top_candidates = build_top_candidates(class_probs)

    class_max_score = np.max(class_probs, axis=-1)
    classes = np.argmax(class_probs, axis=-1)
    class_positions = np.where(class_max_score >= OBJ_THRESH)

    if len(class_positions[0]) == 0:
        return None, None, None, top_candidates

    scores = class_max_score[class_positions]
    bbox = bbox[class_positions]
    classes = classes[class_positions]

    cx, cy, w, h = bbox[:, 0], bbox[:, 1], bbox[:, 2], bbox[:, 3]
    x1 = cx - w / 2
    y1 = cy - h / 2
    x2 = cx + w / 2
    y2 = cy + h / 2
    boxes = np.stack([x1, y1, x2, y2], axis=1)

    kept_boxes = []
    kept_classes = []
    kept_scores = []
    for class_id in set(classes):
        indices = np.where(classes == class_id)
        class_boxes = boxes[indices]
        class_scores = scores[indices]
        class_ids = classes[indices]
        keep = nms_boxes(class_boxes, class_scores)
        if len(keep) > 0:
            kept_boxes.append(class_boxes[keep])
            kept_classes.append(class_ids[keep])
            kept_scores.append(class_scores[keep])

    if not kept_boxes:
        return None, None, None, top_candidates

    return (
        np.concatenate(kept_boxes),
        np.concatenate(kept_classes),
        np.concatenate(kept_scores),
        top_candidates,
    )


def draw_label(image, text, x, y, color):
    font = cv2.FONT_HERSHEY_SIMPLEX
    scale = 0.6
    thickness = 2
    (text_w, text_h), baseline = cv2.getTextSize(text, font, scale, thickness)
    box_top = max(0, y - text_h - baseline - 10)
    box_bottom = max(text_h + baseline + 8, y)
    cv2.rectangle(
        image,
        (x, box_top),
        (x + text_w + 14, box_bottom),
        color,
        -1,
    )
    cv2.putText(
        image,
        text,
        (x + 7, box_bottom - baseline - 4),
        font,
        scale,
        (245, 248, 240),
        thickness,
        cv2.LINE_AA,
    )


def draw(image, boxes, scores, classes, ratio, padding):
    detections = build_detections(boxes, scores, classes, ratio, padding, image.shape)
    colors = [
        (57, 130, 247),
        (46, 168, 120),
        (64, 89, 255),
        (33, 64, 25),
    ]

    for index, detection in enumerate(detections):
        x1, y1, x2, y2 = detection["box"]
        score = detection["score"]
        label = detection["label"]
        color = colors[index % len(colors)]

        cv2.rectangle(image, (x1, y1), (x2, y2), color, 3)
        draw_label(image, translate_label(label), x1, y1, color)
    return detections


def letterbox(image, new_shape=(640, 640), color=(0, 0, 0)):
    shape = image.shape[:2]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)

    ratio_value = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    ratio = ratio_value, ratio_value
    new_unpad = int(round(shape[1] * ratio_value)), int(round(shape[0] * ratio_value))
    dw = new_shape[1] - new_unpad[0]
    dh = new_shape[0] - new_unpad[1]
    dw /= 2
    dh /= 2

    if shape[::-1] != new_unpad:
        image = cv2.resize(image, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    image = cv2.copyMakeBorder(
        image,
        top,
        bottom,
        left,
        right,
        cv2.BORDER_CONSTANT,
        value=color,
    )
    return image, ratio, (left, top)


def detect_frame(rknn_lite, image):
    annotated = image.copy()
    input_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    input_image, ratio, padding = letterbox(input_image)
    input_image = np.expand_dims(input_image, 0)

    outputs = rknn_lite.inference(inputs=[input_image], data_format=["nhwc"])
    boxes, classes, scores, top_candidates = yolov8_post_process(outputs)

    detections = []
    if boxes is not None:
        detections = draw(annotated, boxes, scores, classes, ratio, padding)

    return {
        "image": annotated,
        "detections": detections,
        "top_candidates": top_candidates,
    }


def myFunc(rknn_lite, image):
    result = detect_frame(rknn_lite, image)
    return result["image"]
